# Generated by Django 4.2.16 on 2024-11-29 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
    ]
